# Generated by Django 4.1.2 on 2022-11-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='current_bid',
            new_name='minimum_bid',
        ),
    ]
